public with sharing class AccountDataloadUtility {
    
    //Constants
    public static final String ACCOUNT_SOURCE_SS='SS';
    public static final String ACCOUNT_SOURCE_V21='V21';
    public static final String ACCOUNT_SOURCE_Admin3='Admin3';
    public static final String ACCOUNT_SOURCE_ISeries='ISeries';
    /**Method to validate the business account data changes
* Input : SObject is the interface object
* Output:Returns a map for returnValues.        
*/
    
        }
        
        
        return billingAccount;
        
    }
    
}
